import type { BusinessDetails, Review } from "@/types/business"

// Define a common set of mock reviews for demonstration
const commonReviews: Review[] = [
  {
    id: "rev1",
    userName: "Ahmad Mohammadi",
    rating: 5,
    comment:
      "The food was incredibly delicious. Very cozy atmosphere and excellent service. I will definitely come again.",
    date: "2024/11/05",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "rev2",
    userName: "Fatemeh Ahmadi",
    rating: 4,
    comment: "The food quality was good, but the waiting time was a bit long. Overall, I'm satisfied.",
    date: "2024/11/01",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "rev3",
    userName: "Ali Hosseini",
    rating: 5,
    comment: "Excellent service and very polite staff. It was a great experience.",
    date: "2024/10/17",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const mockBusinessesData: BusinessDetails[] = [
  {
    id: "1",
    name: "Traditional Cafe & Restaurant",
    category: "Restaurant & Cafe",
    description:
      "The best traditional Iranian dishes with excellent quality and a cozy, peaceful atmosphere. We have over 20 years of experience serving you.",
    address: "Tehran, Valiasr Street, No. 123, Ground Floor",
    phone: "+98-21-88776655",
    rating: 4.8,
    reviewCount: 156,
    distance: 0.5,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    services: ["Traditional Food", "Coffee Shop", "Home Delivery", "Online Order", "Catering"],
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Daily 10:00 to 23:00",
    reviews: commonReviews,
    latitude: 35.7654,
    longitude: 51.4123,
  },
  {
    id: "2",
    name: "Modern Men's Barbershop",
    category: "Beauty & Salon",
    description: "Men's grooming services with modern and hygienic equipment. Ask us for the latest styles.",
    address: "Tehran, Tajrish Square, Nouri Alley, No. 10",
    phone: "+98-21-22334455",
    rating: 4.6,
    reviewCount: 89,
    distance: 1.2,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: false,
    services: ["Haircut", "Shave", "Face Massage", "Skin Cleansing"],
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Saturday to Thursday 9:00 to 21:00",
    reviews: commonReviews,
    latitude: 35.7987,
    longitude: 51.4201,
  },
  {
    id: "3",
    name: "Home Appliances Store",
    category: "Shopping & Retail",
    description: "Various home appliances at reasonable prices and valid warranty. Shipping nationwide.",
    address: "Tehran, Grand Bazaar, Home Appliances Section, No. 50",
    phone: "+98-21-33445566",
    rating: 4.3,
    reviewCount: 234,
    distance: 2.1,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    services: ["Home Appliances", "Repairs", "Warranty", "Free Installation"],
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Daily 9:00 to 20:00",
    reviews: commonReviews,
    latitude: 35.6892,
    longitude: 51.389,
  },
  {
    id: "4",
    name: "Paradise Market",
    category: "Shopping & Retail",
    description: "Fresh and organic produce market. Expect the best quality from us.",
    address: "Shop 1/365 Logan Rd, Stones Corner QLD 4120, Australia",
    phone: "0431181021",
    rating: 4.7,
    reviewCount: 120,
    distance: 150.0, // Example distance for Australia
    image: "/images/paradise-market.png",
    isPromoted: true,
    services: ["Fresh Produce", "Fruits & Vegetables", "Organic Products", "Groceries"],
    images: [
      "/images/paradise-market.png",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Mon-Sat: 7:30-20:00 Sun: 8:00-19:00",
    reviews: commonReviews,
    latitude: -27.499644,
    longitude: 153.044794,
  },
  {
    id: "5",
    name: "Toranj Restaurant",
    category: "Restaurant & Cafe",
    description: "Authentic Iranian cuisine with an unparalleled taste and a pleasant ambiance.",
    address: "693 Brunswick St, New Farm QLD 4005, Australia",
    phone: "0734969158",
    rating: 4.9,
    reviewCount: 210,
    distance: 145.0, // Example distance for Australia
    image: "/images/toranj-restaurant.png",
    isPromoted: false,
    services: ["Iranian Food", "Kebab", "Stew", "Tea & Dessert"],
    images: [
      "/images/toranj-restaurant.png",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Daily 12:00 to 22:00",
    reviews: commonReviews,
    latitude: -27.4642967,
    longitude: 153.0394663,
  },
  {
    id: "6",
    name: "Farah Restaurant",
    category: "Restaurant & Cafe",
    description: "A unique experience of Middle Eastern cuisine with exceptional quality.",
    address: "391 Wickham Ter, Spring Hill QLD 4000, Australia",
    phone: "0731725300",
    rating: 4.5,
    reviewCount: 95,
    distance: 148.0, // Example distance for Australia
    image: "/images/farah-restaurant.png",
    isPromoted: true,
    services: ["Middle Eastern Food", "Fast Food", "Salad", "Beverages"],
    images: [
      "/images/farah-restaurant.png",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Daily 11:00 to 21:00",
    reviews: commonReviews,
    latitude: -27.4632558,
    longitude: 153.0185756,
  },
  {
    id: "7",
    name: "Iraj Auto Repair (RWC)",
    category: "Automotive Services",
    description: "Specialized car repairs and RWC certification at the best prices.",
    address: "680 Beaudesert Rd, Rocklea QLD 4106, QLD 4104, Australia",
    phone: "0412544121",
    rating: 4.2,
    reviewCount: 60,
    distance: 160.0, // Example distance for Australia
    image: "/images/iraj-auto-repair.png",
    isPromoted: false,
    services: ["Engine Repair", "Oil Change", "RWC Inspection", "Brake Repair"],
    images: [
      "/images/iraj-auto-repair.png",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    workingHours: "Monday to Friday 8:00 to 17:00",
    reviews: commonReviews,
    latitude: -27.5553195,
    longitude: 153.0186751,
  },
]
