-- Insert sample businesses
INSERT INTO businesses (
  name, category, description, address, phone, email, website, 
  working_hours, services, latitude, longitude, is_promoted, 
  status, image, rating, review_count
) VALUES 
(
  'Paradise Market',
  'grocery',
  'Fresh groceries and daily essentials',
  '123 Main St, Tehran',
  '+98-21-1234567',
  'info@paradisemarket.com',
  'https://paradisemarket.com',
  'Daily 8:00 AM - 10:00 PM',
  ARRAY['Fresh Produce', 'Dairy Products', 'Bakery'],
  35.6892,
  51.3890,
  true,
  'approved',
  '/images/paradise-market.png',
  4.5,
  127
),
(
  'Toranj Restaurant',
  'restaurant',
  'Traditional Persian cuisine in a cozy atmosphere',
  '456 Food Street, Tehran',
  '+98-21-2345678',
  'contact@toranjrestaurant.com',
  'https://toranjrestaurant.com',
  'Daily 12:00 PM - 11:00 PM',
  ARRAY['Dine-in', 'Takeout', 'Delivery'],
  35.7219,
  51.3347,
  false,
  'approved',
  '/images/toranj-restaurant.png',
  4.2,
  89
),
(
  'Farah Restaurant',
  'restaurant',
  'Modern Iranian dishes with international flavors',
  '789 Culinary Ave, Tehran',
  '+98-21-3456789',
  'hello@farahrestaurant.com',
  'https://farahrestaurant.com',
  'Daily 11:30 AM - 10:30 PM',
  ARRAY['Fine Dining', 'Catering', 'Private Events'],
  35.6961,
  51.4231,
  true,
  'approved',
  '/images/farah-restaurant.png',
  4.7,
  156
),
(
  'Iraj Auto Repair',
  'automotive',
  'Professional auto repair and maintenance services',
  '321 Service Road, Tehran',
  '+98-21-4567890',
  'service@irajauto.com',
  'https://irajautorepair.com',
  'Mon-Sat 8:00 AM - 6:00 PM',
  ARRAY['Engine Repair', 'Oil Change', 'Tire Service'],
  35.7589,
  51.4087,
  false,
  'approved',
  '/images/iraj-auto-repair.png',
  4.3,
  73
);
