-- Insert sample businesses
INSERT INTO businesses (
  name, category, description, address, phone, email, website, 
  working_hours, services, latitude, longitude, is_promoted, 
  status, image, rating, review_count
) VALUES 
(
  'Paradise Market',
  'grocery',
  'Fresh groceries and daily essentials',
  '123 Main St, Sydney NSW 2000',
  '+61 2 9876 5432',
  'info@paradisemarket.com.au',
  'https://paradisemarket.com.au',
  'Mon-Sun 7 AM - 10 PM',
  ARRAY['Fresh Produce', 'Groceries', 'Dairy Products'],
  -33.8688,
  151.2093,
  true,
  'approved',
  '/images/paradise-market.png',
  4.5,
  128
),
(
  'Toranj Restaurant',
  'restaurant',
  'Authentic Persian cuisine in the heart of Sydney',
  '456 George St, Sydney NSW 2000',
  '+61 2 9123 4567',
  'contact@toranjrestaurant.com.au',
  'https://toranjrestaurant.com.au',
  'Tue-Sun 5 PM - 11 PM',
  ARRAY['Persian Cuisine', 'Dine-in', 'Takeaway', 'Catering'],
  -33.8650,
  151.2094,
  false,
  'approved',
  '/images/toranj-restaurant.png',
  4.7,
  89
),
(
  'Farah Restaurant',
  'restaurant',
  'Traditional Middle Eastern dishes with modern flair',
  '789 Pitt St, Sydney NSW 2000',
  '+61 2 9234 5678',
  'hello@farahrestaurant.com.au',
  'https://farahrestaurant.com.au',
  'Wed-Mon 6 PM - 12 AM',
  ARRAY['Middle Eastern', 'Halal', 'Vegetarian Options', 'Private Dining'],
  -33.8700,
  151.2080,
  true,
  'approved',
  '/images/farah-restaurant.png',
  4.3,
  156
),
(
  'Iraj Auto Repair',
  'automotive',
  'Professional automotive repair and maintenance services',
  '321 Parramatta Rd, Leichhardt NSW 2040',
  '+61 2 9345 6789',
  'service@irajauto.com.au',
  'https://irajauto.com.au',
  'Mon-Fri 8 AM - 6 PM, Sat 8 AM - 4 PM',
  ARRAY['Engine Repair', 'Brake Service', 'Oil Change', 'Tire Service', 'Electrical Repair'],
  -33.8847,
  151.1547,
  false,
  'approved',
  '/images/iraj-auto-repair.png',
  4.6,
  73
);
