-- Insert sample businesses
INSERT INTO businesses (
  name, category, description, address, phone, email, website, 
  working_hours, services, latitude, longitude, is_promoted, 
  status, image, rating, review_count
) VALUES 
(
  'Paradise Market',
  'Restaurant & Cafe',
  'Authentic Persian grocery store with fresh ingredients and traditional spices',
  '123 Main Street, Toronto, ON',
  '+1 (416) 555-0123',
  'info@paradisemarket.com',
  'https://paradisemarket.com',
  'Mon-Sat: 9AM-9PM, Sun: 10AM-7PM',
  ARRAY['Grocery', 'Fresh Produce', 'Persian Spices', 'Halal Meat'],
  43.6532,
  -79.3832,
  true,
  'approved',
  '/images/paradise-market.png',
  4.5,
  127
),
(
  'Toranj Restaurant',
  'Restaurant & Cafe',
  'Fine Persian dining experience with traditional and modern dishes',
  '456 Queen Street, Toronto, ON',
  '+1 (416) 555-0456',
  'reservations@toranjrestaurant.com',
  'https://toranjrestaurant.com',
  'Daily: 5PM-11PM',
  ARRAY['Fine Dining', 'Persian Cuisine', 'Catering', 'Private Events'],
  43.6426,
  -79.3871,
  true,
  'approved',
  '/images/toranj-restaurant.png',
  4.8,
  203
),
(
  'Farah Beauty Salon',
  'Health & Beauty',
  'Professional beauty services with Persian hospitality',
  '789 Yonge Street, Toronto, ON',
  '+1 (416) 555-0789',
  'appointments@farahbeauty.com',
  'https://farahbeauty.com',
  'Tue-Sat: 10AM-7PM',
  ARRAY['Hair Styling', 'Makeup', 'Eyebrow Threading', 'Facial Treatments'],
  43.6629,
  -79.3957,
  false,
  'approved',
  '/images/farah-restaurant.png',
  4.3,
  89
),
(
  'Iraj Auto Repair',
  'Automotive Services',
  'Trusted automotive repair and maintenance services',
  '321 Dundas Street, Toronto, ON',
  '+1 (416) 555-0321',
  'service@irajauto.com',
  'https://irajauto.com',
  'Mon-Fri: 8AM-6PM, Sat: 9AM-4PM',
  ARRAY['Oil Change', 'Brake Repair', 'Engine Diagnostics', 'Tire Service'],
  43.6505,
  -79.3493,
  false,
  'approved',
  '/images/iraj-auto-repair.png',
  4.6,
  156
);
